apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: git@github.com:silentknight2001/open-flights.git
      sshPrivateKeySecret:
        name: git-credentials
        key: ghp_45N5516xztns0SEtGYA9IjfLdtfX155rWnVT
